Addcourse
nilenso/dhobi-seva-clojure pull request #9
Opened 2017-02-24 08:53 UTC by mayankpahwa

2017-03-02 11:52 UTC, deobald requested changes
sorry! this was the review I forgot to submit,

2017-03-02 11:52 UTC, deobald commented on src/database/core.clj
> +(defn add-Course
`add-course`, not `add-Course` (even if `Course` is a Java type or Protocol... though we can debate this later 😃 )

2017-03-02 11:52 UTC, deobald commented on src/database/core.clj
> +    (if (.exists (io/as-file file-path))
Try to isolate all Java interop into a separate set of namespaces (or just one ns), eventually.

2017-03-02 11:52 UTC, deobald commented on src/database/core.clj
> +                      "students" {}}]
This may be explained later but I'm in a rush... `students` isn't a vector? Why a map?

2017-03-02 11:52 UTC, deobald commented on src/database/core.clj
> +    (let [this-course {"start" start,
Keys of maps should (almost) always be keywords. Definitely prefer keywords to strings.

2017-03-02 11:52 UTC, deobald commented on src/gui/core.clj
> +    (config! f :title "Vipasana"
Usually spelled "vipassana" 😺

2017-03-02 11:52 UTC, deobald commented on src/gui/core.clj
> +        (or (empty? course-name) (empty? start-date) (empty? duration)) (alert "Please enter all the fields")
Eventually (not necessary now), move all validation-related things into their own namespace, including warning/error messages.

2017-03-02 11:52 UTC, deobald commented on src/gui/core.clj
> +        [(label :text "Course Name:" :halign :center :font {:size 20})]
Eventually (not now), move all user-facing text into a single ns so it is easy to translate/isolate.

2017-03-02 11:52 UTC, deobald commented on src/validate/core.clj
> +  (:gen-class))
Nice :)

2017-03-02 11:52 UTC, deobald commented on test/gui/core_test.clj
> +(deftest a-test
There are 2 very easy tests you could write now and a few other (harder) tests that you could try to write, if you want. Ask the group what they think these are and how you might go about writing them.

Do write at least the two easy tests before merging. Otherwise, looks good!

2017-03-10 07:20 UTC, mayankpahwa commented
@deobald Merging this PR. 

To Do:
  - Convert key of maps to keywords instead of strings(as per the discussion yesterday)
  - Write tests

2017-03-10 07:20 UTC, merged